# Site settings
title: Chujie Tian
description: 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chujie Tian
user_description: Bachelor of Economics
#user_title: Student
email: tianchujie@outlook.com
twitter_username: ChujieTian
github_username:  ChujieTian

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
